stages:
  - deploy

deploy-backend:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "master"
  services:
    - docker:dind
  #when: manual
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    # - ssh-add <(echo "$PRIVATE_KEY")
    - echo "$PRIVATE_KEY" > key
    - chmod 600 key
    - ssh-add key
    - rm key
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get install rsync
  script:
    - ssh $USER@$IP './pull.sh'


